
service: serverless-handson

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  
functions:
  rss-reader:
# add your rssReader connection here
  audio-transcoder:
# add your audioTranscoder connection here

resources:
  Resources:
# add the definition of your S3 bucket here
    Article:
# add the definition of your table here

  Outputs:
